### ISSUE TITLE
[Bug]: Python Func Sample caching

### ISSUE THREAD

**Issue by vrdmr** [Azure/azure-functions-vscode-web#31] opened 2024-08-16 17:06 UTC
### Actual Behavior *

<img width="362" alt="image" src="https://github.com/user-attachments/assets/3c336041-6ce4-4fd7-adea-7a259e6f1887">

### Steps to Reproduce

Opening a function app in LL

### Priority

Low (happening rarely)

**Comment by EvanR-Dev** [comment] 2024-08-19 16:49
Dupe of #36 - fixed

**Closed as completed by EvanR-Dev** 2024-08-19 16:49 UTC
Labels: bug, duplicate, triage, limelight
