### ISSUE TITLE
Switches back and forth between Explorer and Extensions views

### ISSUE THREAD

**Issue by bamurtaugh** [Azure/azure-functions-vscode-web#10] opened 2024-08-15 19:45 UTC
- Let my vscode.dev instance go idle
- Lost connection and needed to reload
- I had the Explorer view open as I started this process 
- As it reconnects, it eventually switches over to focusing on the Extensions view

![Image](https://github.com/user-attachments/assets/f37db07c-bf69-4d34-9946-5a43a80fb491)

- Once it fully reconnects, it then focuses back on the Explorer?

I also realize I experience https://github.com/Azure/azure-functions-vscode-web/issues/8 again as I'm told I need to reload due to the Azure Resources extension.

**Comment by EvanR-Dev** [comment] 2024-08-16 04:37
This is by design - it will focus the extensions view until all of them are downloaded and activated. It will then switch back to the file explorer view when done. This is to give the user more clarity on what is happening

**Comment by bamurtaugh** [comment] 2024-08-16 16:54
Ah got it, thanks for the clarity. It was a bit jarring because if extension install was taking a while and I wanted to go explore other things, I'd get forced back into focusing on the Extensions view. I think bringing folks there to show them what's happening can make sense, but then perhaps let the user more freely click around if they choose to change focus?

**Comment by EvanR-Dev** [comment] 2024-08-19 19:11
Closing in favor of #29

**Closed as completed by EvanR-Dev** 2024-08-19 19:11 UTC
Labels: limelight
